services:
  db:
     image: mysql
     container_name: mysql_db
     environment:
        - MYSQL_ROOT_PASSWORD="saharth"
  web:
      image: nginx
      build: .
      depends_on:
        -db
      container_name: nginx_web
      ports:
        -"8080:80"
      ethernets:
          eth0:
              addresses: 
              gateway4: 


